# Generated by Django 5.1.7 on 2025-03-25 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Interest name')),
                ('category', models.CharField(max_length=50, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Interest',
                'verbose_name_plural': 'Interests',
                'unique_together': {('name', 'category')},
            },
        ),
        migrations.CreateModel(
            name='UserInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_weight', models.FloatField(default=1.0, verbose_name='Preference weight')),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.interest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='users.appuser')),
            ],
            options={
                'verbose_name': 'User Interest',
                'verbose_name_plural': 'User Interests',
                'unique_together': {('user', 'interest')},
            },
        ),
    ]
