# Generated by Django 5.1.7 on 2025-03-28 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPTRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('got_response', models.BooleanField(default=False)),
                ('prompt', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpt_requests', to='posts.post')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gpt_requests', to='users.user')),
            ],
        ),
    ]
