from django.db import models
from django.conf import settings
from django.utils.translation import gettext_lazy as _
from frameworks_and_drivers.django.users.models import User


class Post(models.Model):
    STATUS_CHOICES = [
        ('draft', _("Draft")),
        ('published', _("Published")),
        ('archived', _("Archived")),
    ]

    user = models.ForeignKey(
        User, 
        on_delete=models.SET_NULL,
        null=True, 
        blank=True,
        related_name='posts'
    )
    title = models.CharField(_("Title"), max_length=200)
    content = models.TextField(_("Content"))
    generated_by_gpt = models.BooleanField(_("Generated by GPT"), default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(
        _("Status"),
        max_length=20,
        choices=STATUS_CHOICES,
        default='draft'
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _("Post")
        verbose_name_plural = _("Posts")


class PostReaction(models.Model):
    REACTION_CHOICES = [
        ('like', _("Like")),
        ('dislike', _("Dislike")),
    ]

    user = models.ForeignKey(
        User, 
        on_delete=models.CASCADE,
        related_name='reactions'
    )
    post = models.ForeignKey(
        Post, 
        on_delete=models.CASCADE,
        related_name='reactions'
    )
    reaction_type = models.CharField(
        _("Reaction type"),
        max_length=10,
        choices=REACTION_CHOICES
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = _("Post Reaction")
        verbose_name_plural = _("Post Reactions")
        unique_together = ['user', 'post']
